[IV-23-24] documentos objetivo 0
giorgiogiovanni/sh-car-analizer pull request #1
Opened 2023-09-21 09:16 UTC by giorgiogiovanni

descripción para objetivo 0 y documentación de configuración de git y github

2023-09-23 07:34 UTC, JJ requested changes
Por favor, consulta los [errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md), incluyendo:

> Hablar desde el principio de "Quiero hacer una aplicación que haga..." cuando lo que se pide es que se describa un problema.

2023-09-23 07:34 UTC, JJ commented on README.md
> +de compra en sus plataformas de compra para profesionales.
Deberías aclarar un poco en qué consiste el problema. "Monitorizar" no parece que sea un problema que pueda abordarse en esta asignatura, si se trata de "buscar". ¿Se trata de acceder a información poco estructurada y por tanto el problema es procesar esa información?

2023-09-27 06:32 UTC, JJ commented
¿Algún problema con esto? ¿Necesitas alguna aclaración?

2023-09-27 18:23 UTC, giorgiogiovanni commented
Buenas profesor.
Estos dias me ha costado sacar un rato para darle una vuelta a la redacción.
A veces es cierto que es complicado abordar el planteamiento desde los ojos del _cliente_, y estoy pensando con los ojos de la solución que ofrecería.
Espero que de esta manera se entienda mejor el problema, y la redacción sea correcta.

2023-09-28 10:53 UTC, JJ requested changes
Adicionalmente a lo comentado, tienes que tener en cuenta que la lógica de negocio no puede ser simplemente sumas o restas. No sé qué algoritmo se usará para calcular el precio de venta, pero no debe ser ni tan simple como para usar sólo operaciones aritméticas ni tan complejo como para necesitar un algoritmo de IA. Por favor, trata de usar otra vez el proceso de design thinking para ver si este cliente (si tienes conocimiento personal) puede tener algún problema que se pueda resolver, o trata de buscar otro campo.

2023-09-28 10:53 UTC, JJ commented on README.md
> +Soy el dueño de un concesionario de compra/venta de vehículos.
Bien por la identificación del cliente, eso siempre es importante. Es la primera fase de la empatización.

2023-09-28 10:53 UTC, JJ commented on README.md
> +Ultimamente el mercado de compra-venta está muy cambiante y tengo problemas para
Por favor, consulta [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-0.md) donde dice que se traten de evitar: 

> Crear problemas demasiado vagos ("una persona quiere invertir") o simplemente descritos como tales ("el problema del transporte").

En este caso "el problema de valorar la viabilidad". Estos son documentos de trabajo, para empezar a entender el problema en el objetivo siguiente y solucionarlo en los ulteriores. En este caso, es difícil comprender el significado de las tres palabras que lo componen.

2023-09-28 10:53 UTC, JJ commented on README.md
> +valorar la viabilidad de algunas oportunidades de compra. En algunas ocasiones
Por favor, trata de plantear la situación de la forma más precisa posible. Entiendo que el cliente de tu aplicación quiere decidir, dado un vehículo que aparece "en el mercado de ocasión" (¿dónde, exactamente? ¿Tienes datos de tal mercado? Recuerda que se trata de un problema del que se tenga conocimiento personal)

2023-09-28 10:53 UTC, JJ commented on doc/obj0/cumplimiento-obj-0.md
> +### LISTA DE VALIDACIÓN
Esto sólo tiene que ir en el cuerpo del PR

2023-09-28 10:53 UTC, JJ commented on doc/obj0/cumplimiento-obj-0.md
> +* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
... y en el cuerpo debe contestarse, sobre todo en casos donde pueda haber ambigüedad.

2023-10-02 17:33 UTC, JJ commented
¿Algún problema con lo comentado? ¿Quieres intentarlo de nuevo?

2023-10-05 06:03 UTC, giorgiogiovanni commented
He realizado una redacción casi nueva del planteamiento del problema.
Es cierto que es complicado el enfoque porque siempre parece un problema ambiguo, y eso me tiene estancado, aunque estoy trabajando sobre el objetivo 1.

En el caso de que no sea correcto, la idea sería quizás plantear un problema totalmente nuevo, para lo cual tengo alguna idea en la recamara por si fuera necesario.

A la espera de revisión @JJ

2023-10-05 08:12 UTC, JJ requested changes
Por favor, aclara si se trata de un problema de procesamiento de información poco estructurada o de otro tipo de problema; en su caso, reformúlalo de forma que tenga una lógica de negocio suficientemente compleja o aclara la que hay.

2023-10-06 11:08 UTC, giorgiogiovanni commented
descripción cambiada. @JJ

2023-10-06 11:22 UTC, JJ requested changes
Porfa, dale una vueltecilla más.

2023-10-06 11:22 UTC, JJ commented on README.md
> +Soy el dueño de un concesionario de compra/venta de vehículos. Últimamente el
Resuelve estos comentarios; o modificas la línea en la que se hacen o pulsas en "resolve" y pones el commit en el que se han resuelto.

2023-10-06 11:22 UTC, JJ commented on README.md
> +acerca de dichas ofertas.
Por favor, ¿puedes poner explícitamente que el problema es extraer información, de qué páginas suele extraerse y qué es lo que más adelante puedes hacer con ello? REcuerda que te he dicho que lo que hemos hablado no lo tengo que tener presente a la hora de corregir, y mucho menos cuando alguien trabaje en tu objetivo 2.

2023-10-06 11:43 UTC, giorgiogiovanni commented on README.md
> +Soy el dueño de un concesionario de compra/venta de vehículos. Últimamente el
solucionado en d30e64abfea8d53b7efca2583ab2fbd3922b4f8d

2023-10-06 11:49 UTC, giorgiogiovanni commented
listo @JJ

2023-10-06 11:50 UTC, JJ approved these changes
👍 gracias por el esfuerzo. Adelante con el siguiente objetivo.

2023-10-06 12:09 UTC, merged

2023-10-11 09:33 UTC, JJ commented
¿Cómo vas con el siguiente objetivo?

2023-10-19 11:47 UTC, JJ commented
Sería conveniente que comenzaras el objetivo siguiente lo antes posible. Si no, va a ser muy complicado que cumplas los plazos a tiempo.